[package]
name = "aluminium_oxide"
version = "0.1.0"
edition = "2021"
authors = ["Vagmi Mudumbai <vagmi.mudumbai@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5" }
